version: '3.8'

services:
  # Servicio de la Aplicación PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_mvc_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      # Estas variables deben coincidir con tu archivo .env
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_AUTH=false
      - SMTP_SECURE=none
      - SMTP_FROM_NAME="Mi Tienda"
      - SMTP_USERNAME=no-reply@mitienda.com
      - APP_ADMIN_EMAIL=${APP_ADMIN_EMAIL}
    depends_on:
      - db
    networks:
      - app-network

  # Servicio de Base de Datos MySQL
  db:
    image: mysql:8.4
    container_name: php_mvc_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Servicio de captura de correos MailHog
  mailhog:
    image: mailhog/mailhog
    container_name: php_mvc_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # Servidor SMTP
      - "8025:8025" # Interfaz Web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local